// Comprehensive list of services available in the mosque community
export const servicesList = [
  'plumbing',
  'carpentry',
  'tailoring',
  'tutoring',
  'cleaning',
  'electrical',
  'generator repair',
  'event setup',
  'catering',
  'translation',
  'photography',
  'sewing',
  'driving',
  'driving instruction',
  'computer repair',
  'ac repair',
  'painting',
  'masonry',
  'welding',
  'gardening',
  'house sitting',
  'babysitting',
  'elderly care',
  'cooking',
  'baking',
  'web design',
  'graphic design',
  'accounting',
  'tax preparation',
  'legal advice',
  'medical consultation',
  'physiotherapy',
  'massage therapy',
  'personal training',
  'music lessons',
  'language lessons',
  'quran teaching',
  'islamic studies',
  'math tutoring',
  'science tutoring',
  'english tutoring',
  'arabic tutoring',
  'software development',
  'mobile repair',
  'appliance repair',
  'locksmith',
  'pest control',
  'moving assistance',
  'furniture assembly',
  'interior design',
  'landscaping',
  'tree trimming',
  'snow removal',
  'house cleaning',
  'office cleaning',
  'window cleaning',
  'carpet cleaning',
  'pressure washing',
  'auto repair',
  'tire service',
  'oil change',
  'car wash',
  'motorcycle repair',
  'bicycle repair',
  'jewelry repair',
  'watch repair',
  'shoe repair',
  'alteration',
  'dry cleaning',
  'laundry service',
  'ironing service',
  'printing service',
  'copying service',
  'document translation',
  'notary service',
  'real estate',
  'property management',
  'insurance agent',
  'financial planning',
  'business consulting',
  'marketing services',
  'social media management',
  'event planning',
  'wedding planning',
  'party planning',
  'decoration service',
  'flower arrangement',
  'gift wrapping',
  'delivery service',
  'courier service',
  'pickup and drop',
  'airport shuttle',
  'grocery shopping',
  'errand running',
  'pet sitting',
  'dog walking',
  'pet grooming',
  'veterinary service',
  'handyman',
  'cleaning',
  'gardening',
  'landscaping',
  'painting',
  'carpentry',
  'roofing',
  'hvac',
  'pest control',
  'home repair',
  'appliance repair',
  'locksmith',
  'pool maintenance',
  'window cleaning',
  'gutter cleaning',
  'pressure washing',
  'flooring',
  'tiling',
];
